### ISSUE TITLE
Make imports nicer

### ISSUE THREAD

**Issue by Sohva** [Sohva/TensorDSL#19]

**Comment by ReubenHill** [comment]
Are you using `Revise.jl` and importing using `using PkgNameHere`? And have you added your path to the package manager as a development package?

**Comment by Sohva** [comment]
No, currently I am just importing everything with include statements. I assume these things you mention are something I should do, is there anything else?

**Comment by ReubenHill** [comment]
See https://docs.julialang.org/en/v1/manual/workflow-tips/

**Comment by Sohva** [comment]
Thank you!
